version: "3.7"
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: clave123
      MYSQL_DATABASE: democrud
      MYSQL_USER: admin
      MYSQL_PASSWORD: clave123
      TZ: America/Santiago
    volumes:
      - ./datadir:/var/lib/mysql
  db-oracle:
    image: container-registry.oracle.com/database/enterprise:latest
    restart: always
    environment:
    - ORACLE_SID=ORCLCDB
    - ORACLE_PDB=ORCLPDB1
    - ORACLE_PWD=oracle
    ports:
      - 1521:1521
    volumes:
    - oracle-data:/opt/oracle/oradata
    - oracle-backup:/opt/oracle/backup
volumes:
  oracle-data:
  oracle-backup: