spring:
  datasource:
    url: jdbc:mysql://localhost:3306/democrud?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: clave123
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update